export class RcvGridConfig {
    public MASTER = [
        { caption: 'uid', dataField: "uid", width: 300, fixed: true, visible: false },
        { caption: 'companyName', dataField: "companyName", width: 300, fixed: false, visible: true },
        { caption: 'name', dataField: "name", width: 300, fixed: false, visible: true },
        { caption: 'tenant', dataField: "tenant", width: 300, fixed: false, visible: true },
        { caption: 'ownoranotherflg', dataField: "ownoranotherflg", width: 300, fixed: false, visible: true },
        { caption: 'transportpriority', dataField: "transportpriority", width: 300, fixed: false, visible: true },
        { caption: 'ownercustomercd', dataField: "ownercustomercd", width: 300, fixed: false, visible: true },
        { caption: 'ownersuppliercd', dataField: "ownersuppliercd", width: 300, fixed: false, visible: true },
        { caption: 'itemadmin', dataField: "itemadmin", width: 300, fixed: false, visible: true },
        { caption: 'actflg', dataField: "actflg", width: 300, fixed: false, visible: true },
        { caption: 'companycd', dataField: "companycd", width: 300, fixed: false, visible: true },
        { caption: 'countrycd', dataField: "countrycd", width: 300, fixed: false, visible: true },
        { caption: 'postno', dataField: "postno", width: 300, fixed: false, visible: true },
        { caption: 'districtcd', dataField: "districtcd", width: 300, fixed: false, visible: true },
        { caption: 'portcd', dataField: "portcd", width: 300, fixed: false, visible: true },
        { caption: 'refname', dataField: "refname", width: 300, fixed: false, visible: true },
        { caption: 'address1', dataField: "address1", width: 300, fixed: false, visible: true },
        { caption: 'address2', dataField: "address2", width: 300, fixed: false, visible: true },
        { caption: 'address3', dataField: "address3", width: 300, fixed: false, visible: true },
        { caption: 'f_USER3', dataField: "f_USER3", width: 300, fixed: false, visible: true },
        { caption: 'f_USER5', dataField: "f_USER5", width: 300, fixed: false, visible: true },
        { caption: 'companygroup', dataField: "companygroup", width: 300, fixed: false, visible: true },
        { caption: 'typecustomer', dataField: "typecustomer", width: 300, fixed: false, visible: true },
        { caption: 'f_USER4', dataField: "f_USER4", width: 300, fixed: false, visible: true },
        { caption: 'phone1', dataField: "phone1", width: 300, fixed: false, visible: true },
        { caption: 'phone2', dataField: "phone2", width: 300, fixed: false, visible: true },
        { caption: 'typesupplier', dataField: "typesupplier", width: 300, fixed: false, visible: true },
        { caption: 'typeshipto', dataField: "typeshipto", width: 300, fixed: false, visible: true },
        { caption: 'typecarrier', dataField: "typecarrier", width: 300, fixed: false, visible: true },
        { caption: 'typeetc', dataField: "typeetc", width: 300, fixed: false, visible: true },
        { caption: 'typewarehouse', dataField: "typewarehouse", width: 300, fixed: false, visible: true },
        { caption: 'f_USER1', dataField: "f_USER1", width: 300, fixed: false, visible: true },
        { caption: 'typeowner', dataField: "typeowner", width: 300, fixed: false, visible: true },
        { caption: 'f_USER2', dataField: "f_USER2", width: 300, fixed: false, visible: true },
        { caption: 'f_USER10', dataField: "f_USER10", width: 300, fixed: false, visible: true },
        { caption: 'purchasetype', dataField: "purchasetype", width: 300, fixed: false, visible: true },
        { caption: 'ownerrefflg', dataField: "ownerrefflg", width: 300, fixed: false, visible: true },
        { caption: 'f_USER8', dataField: "f_USER8", width: 300, fixed: false, visible: true },
        { caption: 'f_USER6', dataField: "f_USER6", width: 300, fixed: false, visible: true },
        { caption: 'f_USER9', dataField: "f_USER9", width: 300, fixed: false, visible: true },
        { caption: 'f_USER7', dataField: "f_USER7", width: 300, fixed: false, visible: true },
        { caption: 'calendarcd', dataField: "calendarcd", width: 300, fixed: false, visible: true },
        { caption: 'bsnumber', dataField: "bsnumber", width: 300, fixed: false, visible: true },
        { caption: 'fax1', dataField: "fax1", width: 300, fixed: false, visible: true },
        { caption: 'email', dataField: "email", width: 300, fixed: false, visible: true },
        { caption: 'aname', dataField: "aname", width: 300, fixed: false, visible: true },
        { caption: 'sname', dataField: "sname", width: 300, fixed: false, visible: true },
        { caption: 'fax2', dataField: "fax2", width: 300, fixed: false, visible: true },
        { caption: 'CREATEDBY', dataField: "CREATEDBY", width: 300, fixed: false, visible: true },
        { caption: 'CREATEDDATE', dataField: "CREATEDDATE", width: 300, fixed: false, visible: true },
        { caption: 'CREATEIP', dataField: "CREATEIP", width: 300, fixed: false, visible: true },
        { caption: 'LASTMODIFIEDBY', dataField: "LASTMODIFIEDBY", width: 300, fixed: false, visible: true },
        { caption: 'LASTMODIFIEDDATE', dataField: "LASTMODIFIEDDATE", width: 300, fixed: false, visible: true },
        { caption: 'LASTMODIFIEDIP', dataField: "LASTMODIFIEDIP", width: 300, fixed: false, visible: true },
        { caption: 'UTC', dataField: "UTC", width: 300, fixed: false, visible: true },
        { caption: 'REMARKS', dataField: "REMARKS", width: 300, fixed: false, visible: true },
        { caption: 'ROW_VERSION', dataField: "ROW_VERSION", width: 300, fixed: false, visible: true },
        { caption: 'TENANT', dataField: "TENANT", width: 300, fixed: false, visible: true },
    ]
    public DETAIL = [
        { caption: 'uid', dataField: "uid", width: 200, fixed: true, visible: true, allowEditing: false },
        { caption: 'tenant', editCellTemplate: '', dataField: "tenant", width: 200, fixed: false, visible: true, allowEditing: false },
        { caption: 'detailname2', editCellTemplate: 'SH_PTNRKEY', dataField: "CODEB", width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'detailname3', editCellTemplate: '', dataField: "CODEC", width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'detailname4', editCellTemplate: '', dataField: "CODED", width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'detailname5', editCellTemplate: '', dataField: "CODEE", width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'detailname6', editCellTemplate: '', dataField: "CODEF", width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'detailname7', editCellTemplate: '', dataField: "CODEG", width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'detailname8', editCellTemplate: '', dataField: "CODEH", width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'detailname9', editCellTemplate: '', dataField: "CODEI", width: 200, fixed: false, visible: true, allowEditing: true },
    ]
}